[package]
name = "cql_db"
version = "0.1.0"
authors = ["Andrew Sisley"]
edition = "2018"

[lib]
name = "cql_db"
path = "src/cql_db.rs"

[dev-dependencies]
serial_test = "*"
byteorder = "1"

[dependencies]
cql_model = { path = "../cql_model" }
cql_storage = { path = "../cql_storage" }
itertools = "0.8.0"
