[package]
name = "cql_db"
version = "0.1.0"
authors = ["Andrew Sisley"]
edition = "2018"
license = "MIT"

[lib]
name = "cql_db"
path = "src/cql_db.rs"

[dependencies]
cql_model = { path = "../cql_model" }
cql_u64 = { path = "../cql_storage_types/cql_u64" }
