[package]
name = "cql_db"
version = "0.1.0"
authors = ["Andrew Sisley <asisley@jaguarlandrover.com>"]
edition = "2018"

[dependencies]
cql_storage = { path = "../cql_storage" }
itertools = "0.8.0"
