[package]
name = "cql_kotlin"
version = "0.1.0"
authors = ["Andrew Sisley"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]

[dependencies]
cql_db = { path = "../cql_db" }
libc = "0.2"
